services:
  web:
    build: .
    command: './entrypoint.sh'
    volumes:
      - .:/app
    ports:
      - "${COMPOSE_PORT:-3000}:3000"
    env_file:
      - .env
    depends_on:
      - redis
      - sidekiq
    environment:
      REDIS_URL: redis://redis:6379/0

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
    env_file:
      - .env

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
